### ISSUE TITLE
Missing artist

### ISSUE THREAD

**Issue by Tillerino** [Francesco149/oppai#13]
I am getting a `Missing artist in metadata` error for this map:
- FamilyMart Jingle (mapped by deepsea)
  http://osu.ppy.sh/b/37658

Thing is: it's true, this map doesn't have an artist. However it's _freakin ranked_ (Kappa), so what do we do now?

**Comment by Francesco149** [comment]
LOL I guess I have to disable that check, sec

**Comment by Francesco149** [comment]
should be fixed, thanks for the report!

**Comment by Tillerino** [comment]
Thx
