### ISSUE TITLE
windows doesnt understand that #pragma

### ISSUE THREAD

**Issue by omkelderman** [Francesco149/oppai#19]
![](https://omk.pics/1/39V6S.png)

**Comment by omkelderman** [comment]
**disclaimer: I know almost nothing of this `#pragma` and `pack` stuff, I literally just googled it to know what `pack` does.**

After reading https://msdn.microsoft.com/en-us/library/2e70t5y1.aspx?f=255&MSPPError=-2147217396 looks like you should use:

```
// instead of #pragma push(pack, 1)
#pragma pack(push, SOMETHING_RANDOM, 1)

// instead of #pragma pop(pack)
#pragma pack(pop, SOMETHING_RANDOM)
```

where `SOMETHING_RANDOM` literally is something random xd. Just to name the thing you push on the stack so you can pop it later. And since I'm uberbad at names, I just got stuck at "SOMETHING_RANDOM". So _if this is indeed what you want_ (**please check this, my knowledge of this stuff is almost zero**) replace it with something more sensible i guess xd.

**Comment by Francesco149** [comment]
well that's weird, I've been using pragma push and pop my entire life, I guess it's deprecated. fixing in a sec

**Comment by omkelderman** [comment]
yeah, idk, like I said, I dont know anything about this stuff, im just googling errors i get xd. So whatever you do, if you copy what I just said, please make sure it does what you want

**Comment by omkelderman** [comment]
oh, and after reading a bit, it _looks like_ (once again, check this xd) that "SOMETHING_RANDOM" thing is optional, so you can probably just omit it...

**Comment by Francesco149** [comment]
oh I'm actually misremembering, it was #pragma pack( push, 1 ) and #pragma pack(pop)

**Comment by omkelderman** [comment]
ah ok, so thats pretty much with omitting that identifier thing like I said in my last comment xd 👍 
TIL something more about pragma's 😄

**Comment by omkelderman** [comment]
rip typo in commit message, issue isnt closed
