### ISSUE TITLE
PP calculation formulas

### ISSUE THREAD

**Issue by DevilLord41** [Francesco149/oppai#22]
Sorry if post here, i dont know how to PM in github,
Can you make code of pp calculation in JS/Java version?
I need the formulas, anyway thanks.

**Comment by ekgame** [comment]
JavaScript implementation: https://github.com/oamaok/osu-pp-calculator
Java implementation: https://github.com/ekgame/beatmap-analyzer

**Comment by Francesco149** [comment]
as ekgame pointed out, you can use https://github.com/oamaok/osu-pp-calculator as a base
