### ISSUE TITLE
Max combo wrong

### ISSUE THREAD

**Issue by HyperBCS** [Francesco149/oppai#23]
In this map the max combo is 2216. Oppai says it is 2240.

**Comment by HyperBCS** [comment]
Changed (num_beats - 0.01) / sl.repetitions \* b.tick_rate); to 
(num_beats - 0.1) / sl.repetitions \* b.tick_rate);

Not sure if this is the correct approach though. Could cause issues with other maps

**Comment by Francesco149** [comment]
sorry for the late reply. do you still have examples of maps that suffer from this problem? bumping it up to 0.1 might be a little too much

**Comment by HyperBCS** [comment]
https://osu.ppy.sh/b/1114721

**Comment by Francesco149** [comment]
well, I adopted your fix for now. I can only assume it's a rounding issue with extremely short or extremely long sliders.
