### ISSUE TITLE
How to get Aim and Speed value?

### ISSUE THREAD

**Issue by DevilLord41** [Francesco149/oppai#24]
Im looking for how to get aim and speed value, please explain to me if you have a time, thanks,

**Comment by Francesco149** [comment]
What do you mean by "getting" them? oppai already outputs aim/speed pp as well as aim/speed stars. You can use json output (-ojson) if you need to parse and feed them into a program.

**Comment by DevilLord41** [comment]
Count the aim and speed difficult value, i wanted to know how to  count them.

**Comment by Francesco149** [comment]
get them from the oppai output?

**Comment by DevilLord41** [comment]
no, im tried to convert this oppai no other application else, im fine with the accuracy difficulty value, but im confuse how to count aim & speed diff value,i see ur code it have calculateStrains, decaybase etc.
and oppai output is a milk la

**Comment by Francesco149** [comment]
reading diff_calc.cc is probably simpler than any explanation I could give. the code speaks by itself. personally I would just call oppai with -ojson so you can get aim/speed values from the json output easily without having to calculate them yourself.
