### ISSUE TITLE
liboppai

### ISSUE THREAD

**Issue by emmiegit** [Francesco149/oppai#31]
Do you think it's worthwhile to create some externally-linkable functions and make an API that others could link to for use in their applications?

**Comment by Francesco149** [comment]
latest commit that i pushed earlier introduces a lib mode that lets you include main.cc with OPPAI_LIB=1 defined and call oppai functions from c++ code. this should be enough to create bindings for other langs and wrap oppai in a shared/static library where including c++ code is not an option.

I'll make bindings for some language, maybe python or golang to test this draft of the lib mode.

**Comment by emmiegit** [comment]
Interesting. I'll try it out. Are there going to be any guarentees about API stability?

**Comment by Francesco149** [comment]
for now it's a draft with no documentation, but I don't see the API changing unless I find major issues with the thread safe refactoring I did.

see lib_example for a minimal program that uses oppai to calc stars & pp.

**Comment by Francesco149** [comment]
yep the current lib mode draft passes the test. I was able to easily throw together python bindings by just including main.cc and python's stuff. didn't even have to wrap it in a shared lib:

![](http://hnng.moe/f/Ppg)

and I've never done python bindings before.

will publish python binds when I get time to test on windows and add some missing stuff

**Comment by Francesco149** [comment]
https://github.com/Francesco149/oppai/tree/master/pyoppai

experimental python2.7 bindings, readme and python3 port coming soon

**Comment by Francesco149** [comment]
node bindings: https://github.com/Francesco149/oppai/tree/master/node-oppai

I think this can be closed now that I have bindings for two of the most mainstream scripting langs

**Comment by emmiegit** [comment]
Very fast. Nice work.
