### ISSUE TITLE
Adding hidden doesn't increase pp. [node-oppai]

### ISSUE THREAD

**Issue by xxxzelda101xxx** [Francesco149/oppai#36]
For some reason, adding hidden doesn't change the pp value. I tested with hr and dt and they both calculate properly. bug?

**Comment by Francesco149** [comment]
are you sure you passed hidden to both applyMods and ppCalc? by the way, mods that don't actually modify the map (anything that isn't HT/DT HR/EZ) don't need applyMods, but you still need to pass them to ppCalc

**Comment by Francesco149** [comment]
oops. I just realized, I never added a mods parameters to ppCalc, LOL will fix

**Comment by Francesco149** [comment]
for a sec I thought I didn't add the mods parameter for ppCalc to the binding, but it's just an optional param that defaults to nomod.

you can find the full optional parameters for ppCalc here: https://github.com/Francesco149/oppai/tree/master/node-oppai/docs#ppcalc

**Comment by xxxzelda101xxx** [comment]
Ok, I'm just dumb. I forgot to also pass the mods to the ppCalc. (k i l l m e)

**Comment by Francesco149** [comment]
yeah I thought so.

it's kinda confusing if you don't know how diff calc and pp calc works
