### ISSUE TITLE
annoying "fopen: No such file or directory" output when running oppai

### ISSUE THREAD

**Issue by jamuwu** [Francesco149/oppai#38]
```oppai uhh.osu -ojson +HDHR 99.34%
fopen: No such file or directory
{"oppai_version":"0.9.5","artist":"Komiya Mao","title":"(can you) understand me?","version":"uhh?","creator":"Sotarks","mods_str": "+HDHR","od":10,"ar":10,"cs":5.45,"hp":8.67,"combo": 439,"max_combo": 439,"num_circles": 174,"num_sliders": 131,"num_spinners": 0,"misses": 0,"score_version": 1,"stars": 5.7100678584207669,"speed_stars": 2.1866054254630947,"aim_stars": 3.0778434304594797,"rhythm_awkwardness": 1.2105010286350117,"nsingles": 293,"nsingles_timing": 304,"nsingles_threshold": 304,"pp":269.26079658519092}```

**Comment by Francesco149** [comment]
newer versions have a caching system that writes and reads pre-parsed beatmaps from disk.

That warning is in stderr by the way, so it shouldn't affect any software trying to parse json output from stdout.

To remove the warning, you can:
- allow the user who is running oppai to create folders and write files in the folder where the oppai executable is located
- run oppai with ```-no-cache``` to disable cache and force it to reparse the .osu file every time

**Comment by omkelderman** [comment]
> allow the user who is running oppai to create folders and write files in the folder where the oppai executable is located

Not gonna happen when the executable is located in `/usr/local/bin` or something simulair.

I propose a different model:
Have a `--cache-dir=...` option. If its present, use it, on that location. If its not present, dont use cache. Simple, clean, no confusion and it wont break existing things.

I always thought that whole `get_exe_path` thing made no sense whatsoever... Even if you're doing something like that, at least take the working directory or something, not the exe-path... 😕

**Comment by Francesco149** [comment]
it already doesn't break anything though, other than that harmless warning

hmm I usually prefer having software self contained in a folder and then symlinking it to /usr/local/bin and such

working dir would be a really bad idea, you're never gonna call oppai from the same directory as a user (unless you're a server or something that runs it automatically)

but sure, I will eventually add a param to change the cache path to something else

**Comment by omkelderman** [comment]
> it already doesn't break anything though, other than that harmless warning

pretty annoying if you ask me 😛 (I havent checked, but I hope its on stderr otherwise it will fuck up json parsing)

> hmm I usually prefer having software self contained in a folder and then symlinking it to /usr/local/bin and such

Well usually when installing a some software the binary gets dropped in some /usr(/local)/bin dir (deb packages do this, `sudo make install` scripts do this) aka, in a "normal" workflow your "having software self contained in a folder" is probably not gonna happen xD

> working dir would be a really bad idea

Totally agree, but its better imo than exe-dir 😛 which imo almost never works well.
New idea for better default: `~/.cache/oppai` (would be `%APPDATA%\oppai` on windows)

> but sure, I will eventually add a param to change the cache path to something else

Sounds good 👌👍

**Comment by Francesco149** [comment]
it is on stderr, as I said in the 1st reply

well, I'm not using any make in my project, so the normal way to install oppai is to ./build.sh or build.bat and then use the exe in place, or download the binaries and create a link to the exe. Building & linking is how I use it and it's perfect for the exe-dir method. On windows you would either cmd to oppai's folder or add it to PATH (better, but not user-friendly) and that would also work with exe-dir.

a package manager would probably drop it in /opt/ or some other folder and symlink it, like older wine does when it's installed through a package manager (other examples are dropbox, firefox-bin, vmware...) , which would work perfectly with the exe-dir method, but honestly it's so easy to just compile it that it feels pointless to use a package manager, especially when there are no dependencies to manage.

I really don't like the standard .config/blahblahblah path convention on linux, it's annoying to have the program split between two folders. maybe i'll just have a .oppairc in home (and appdata on windows) to set the default values for each param so it's easier to make a custom cache folder stick

well we'll see next time I'm working on this

**Comment by omkelderman** [comment]
wops, im blind sorry

and about the rest of your story. I totally get it, and when talking about make/package manager stuff I was just point out how other stuff does it

And more to the point: its what I'm used to 😉

We just have a different opinion on things, and thats fine 😄

You just do whatever you think fits for this project, and I'll worry about adjusting it to my use case I guess xD

(quick sidenote a .oppairc is something I wouldnt like hahaha)
