### ISSUE TITLE
Cache use. 

### ISSUE THREAD

**Issue by TheMeq** [Francesco149/oppai#45]
I don't understand how to make use of the cache. If my oppai has already downloaded the osu file, how do I then use that in subsequent calls? Do I specify the beatmap id after oppai.exe? 

Some clarification would be nice. Thanks.

**Comment by Francesco149** [comment]
it's automatic. if the cache is enabled, once a map has been parsed once (most expensive part of an oppai call) it will be saved in the oppai_cache folder in a pre-parsed binary format and loaded from there instead if you call oppai again on the same .osu file

**Comment by Francesco149** [comment]
closing this, reopen if you still have issues
