### ISSUE TITLE
inf pp

### ISSUE THREAD

**Issue by omkelderman** [Francesco149/oppai#48]
map: https://osu.ppy.sh/b/1258033&m=0

for some reason (I havent played the map, if I will it'll probably be obvious) this thing has a shitton of stars:
(*interesting sidenote: website/osu-api displays it as zero stars*)
```
stars: 5.62916e+94
aim stars: 3.75277e+94
speed stars: 4.39004e+59

aim: 2.71601e+284
speed: 4.34789e+179
```

which results in a pp value of infinite: `infpp`

Which in itself isnt that bad honestly, but it is a problem when doing json output:
```
{"oppai_version":"0.9.6","artist":"Helblinde","title":"The Solace of Oblivion","version":"Aspire","creator":"MinG3012","mods_str": "","od":8.68,"ar":9.35,"cs":3.99,"hp":2.55,"combo": 16727,"max_combo": 16727,"num_circles": 737,"num_sliders": 767,"num_spinners": 4,"misses": 0,"score_version": 1,"stars": 5.6291586263016401e+94,"speed_stars": 4.3900365064717424e+59,"aim_stars": 3.7527724175344267e+94,"rhythm_awkwardness": nan,"nsingles": 959,"nsingles_timing": 1415,"nsingles_threshold": 1038,"pp":inf}
```
Since because of the `inf` value of pp and the `nan` value of "rhythm_awkwardness" it is not valid json anymore 😞 

Replace `inf` and `nan` with `null` or something since that *is* valid json? Idk, probably stupid idea, but I have no idea how to handle such cases in a "true json" way....

**Comment by Francesco149** [comment]
lol we are really pushing the limits right here

guess I will figure out how to test for NaN, thanks for reporting

**Comment by Francesco149** [comment]
this should be the way to test for NaN and inf, and I will probably return null in json when that happens

https://www.doc.ic.ac.uk/~eedwards/compsys/float/nan.html

**Comment by Francesco149** [comment]
I've decided to instead output the maximum value for inf and zero for NaN. even if they don't mathematically make sense, it avoids annoying custom logic for whoever needs to use the json output

**Comment by Francesco149** [comment]
python seems to handle this just fine, guess i'll push the fix

```
$ curl https://osu.ppy.sh/osu/1258033 2>/dev/null | ./oppai - -ojson | python -c "import json, sys; print(json.dumps(json.loads(sys.stdin.read()), indent=4))"
{
    "num_spinners": 4, 
    "mods_str": "", 
    "creator": "MinG3012", 
    "nsingles_threshold": 1036, 
    "ar": 9.35, 
    "cs": 3.99, 
    "num_circles": 737, 
    "speed_stars": 4.390036506471742e+59, 
    "aim_stars": 3.752772417534427e+94, 
    "pp": 1.7976931348623157e+308, 
    "title": "The Solace of Oblivion", 
    "misses": 0, 
    "version": "Aspire", 
    "stars": 5.62915862630164e+94, 
    "combo": 16727, 
    "oppai_version": "0.9.9", 
    "max_combo": 16727, 
    "hp": 2.55, 
    "nsingles": 959, 
    "score_version": 1, 
    "artist": "Helblinde", 
    "od": 8.68, 
    "nsingles_timing": 1411, 
    "num_sliders": 767
}
```
