### ISSUE TITLE
pyoppai error: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by Syriiin** [Francesco149/oppai#49]
I have been able to install pyoppai on linux, but the windows installation with git bash throws this error. 

Full output:
```
$ python setup.py install
running install
running build
running build_ext
building 'pyoppai' extension
error: Unable to find vcvarsall.bat
```

**Comment by Francesco149** [comment]
I'm not familiar with building native stuff for python on windows, but it seems like setup tools can't find a working MSVC compiler (vcvarsall is used to initialize the environment vars for the compiler).

EDIT: NEVERMIND there's a specific version for python 2.7: https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by Syriiin** [comment]
Alright, that fixed the `error: Unable to find vcvarsall.bat`, but then there was:
```
$ python setup.py install
...
Generating code
Finished generating code
LINK : fatal error LNK1158: cannot run 'rc.exe'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1158
```

I was able to fix this however by copying `rc.exe` and `rcdll.dll` from `C:\Program Files (x86)\Windows Kits\8.1\bin\x64\` to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\`

Thanks for the help
