### ISSUE TITLE
TouchDevice MOD(TD) should be included now

### ISSUE THREAD

**Issue by kj415j45** [Francesco149/oppai#65]
Recently, TouchDevice(TD) replace previous NoVideo in `enable_mods`, some nerfed algorithm apply to this MOD when calculate pp (ACC). I hope when I pass `+TD` to oppai, it could give me correct answer. Waiting for your updates :)

**Comment by omkelderman** [comment]
this repo is outdated, see https://github.com/Francesco149/oppai-ng for the up to date version

**Comment by jamuwu** [comment]
Edit: oof I was sniped

**Comment by kj415j45** [comment]
didn't noticed :v
